[agent]
  interval = "1s"
  flush_interval = "1s"

# ══════════════ SUROWA TELEMETRIA ══════════════

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["robot/gps"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["robot_id", "latitude", "longitude", "altitude"]
  csv_tag_columns = ["robot_id"]
  name_override = "gps_raw"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["robot/odom"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["robot_id", "linear_x", "angular_z"]
  csv_tag_columns = ["robot_id"]
  name_override = "odom_raw"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["robot/battery"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["robot_id", "voltage", "percentage", "current"]
  csv_tag_columns = ["robot_id"]
  name_override = "battery_raw"

# ══════════════ ALERTY ══════════════

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["robot/alerts"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["robot_id", "latitude", "longitude"]
  csv_tag_columns = ["robot_id"]

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["soil/alerts"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["temp_10cm", "temp_20cm"]
  csv_tag_columns = []

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["robot/odom_alerts"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["robot_id", "linear_x", "angular_z"]
  csv_tag_columns = ["robot_id"]

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["robot/battery_alerts"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["robot_id", "voltage", "percentage"]
  csv_tag_columns = ["robot_id"]

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["robot/collision_alerts"]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["robot_id_a", "robot_id_b", "lat", "lon"]
  csv_tag_columns = ["robot_id_a", "robot_id_b"]
  name_override = "collision_alerts"

# ══════════════ OUTPUT ══════════════

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "mytoken123"
  organization = "robotics"
  bucket = "geofencing"
